spring:
  application:
    name: btg-funds-backend-mongo
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/btg_funds}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
